name: postgres
services:
  psql:
    image: n1f7/psql:amd64-surface
    volumes:
      - .\psql_history:/root/.psql_history
    stdin_open: true
    tty: true
    build:
      context: config/surface
      dockerfile: ../../Dockerfile
    restart: "no"