name: postgres
services:
  psql:
    image: n1f7/psql:amd64
    build:
      target: app
      args:
        target: amd64
    configs:
      - source: psqlrc
        target: /etc/postgresql-15/psqlrc
configs:
  psqlrc:
    file: ./.psqlrc
