name: psql
services:
  console:
    image: n1f7/psql-gentoo:latest
    volumes:
      - ./make.conf:/etc/portage/make.conf
    stdin_open: true
    tty: true
    build:
      context: .
    restart: "no"