name: postgres
services:
  psql:
    image: n1f7/psql:amd64
    network_mode: host
    build:
      target: squashed
      args:
        target: amd64
    configs:
      - source: psqlrc
        target: /etc/postgresql-15/psqlrc
configs:
  psqlrc:
    file: ./.psqlrc
