FROM scratch AS app
COPY --from=postgres:latest /etc/inputrc /etc/ld.so.cache																																																																																																																																																																																																/etc/
COPY --from=postgres:latest /lib64/ld-linux-x86-64.so.2																																																																																																																																																																																																/lib64/
COPY --from=postgres:latest /usr/lib/x86_64-linux-gnu/libpq.so.5 /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 /usr/lib/x86_64-linux-gnu/libkrb5.so.3 /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 /usr/lib/x86_64-linux-gnu/libsasl2.so.2 /usr/lib/x86_64-linux-gnu/libgnutls.so.30 /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 /usr/lib/x86_64-linux-gnu/libidn2.so.0 /usr/lib/x86_64-linux-gnu/libunistring.so.2 /usr/lib/x86_64-linux-gnu/libtasn1.so.6 /usr/lib/x86_64-linux-gnu/libnettle.so.8 /usr/lib/x86_64-linux-gnu/libhogweed.so.6 /usr/lib/x86_64-linux-gnu/libgmp.so.10 /usr/lib/x86_64-linux-gnu/libffi.so.7		/usr/lib/x86_64-linux-gnu/
COPY --from=postgres:latest /usr/lib/postgresql/15/bin/psql																																																																																																																																																																																															/usr/lib/postgresql-15/bin/
COPY --from=postgres:latest /lib/x86_64-linux-gnu/libreadline.so.8 /lib/x86_64-linux-gnu/libpthread.so.0 /lib/x86_64-linux-gnu/libm.so.6 /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libcom_err.so.2 /lib/x86_64-linux-gnu/libresolv.so.2 /lib/x86_64-linux-gnu/libkeyutils.so.1																																																																																																																						/lib/x86_64-linux-gnu/
COPY --from=postgres:latest /usr/lib/locale/locale-archive																																																																																																																																																																																															/usr/lib/locale/
ENV LANG=en_GB.utf8
VOLUME /root/.psql_history
ENTRYPOINT ["/usr/lib/postgresql-15/bin/psql"]
CMD ["-h", "nas.nostromo.shemyakin.me", "-p", "5433", "-U", "postgres"]